spring.application.name=ChatGPT-integration
spring.autoconfigure.exclude=none

gpt.chat.temperature=1.0
gpt.chat.presence.penalty=1.0
gpt.chat.api.url=https://api.openai.com/v1/chat/completions
gpt.chat.qty.context.messages=2
gpt.chat.sendrequest.retryattempts=1
gpt.chat.sendrequest.waitforretry.seconds=5

#JIRA
jira.url=https://mtroja98.atlassian.net/rest/api/3
jira.issue=/issue
jira.search=/search/jql
jira.project.name=JAVA
jira.max.results=3
jira.fields=summary,description,assignee,status,issuetype
jira.retry.attempts=2
jira.wait.seconds=5
jira.create.issue.endpoint=/issue

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

logging.level.org.springframework.security=INFO

## HIBERNATE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql=ERROR
logging.level.org.hibernate.orm.jdbc.bind=ERROR

spring.main.banner-mode=console
logging.level.root=INFO

# TESTS

spring.main.allow-bean-definition-overriding=true

# GITHUB

github.api.url=https://api.github.com

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

