name: Build and Deploy Spring Boot App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Full clone for GitVersion
        run: |
          rm -rf /tmp/repo
          git clone https://github.com/m-troja/ChatGPT-SpringBoot.git /tmp/repo --branch main

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v4
        with:
          versionSpec: '6.x'
      
      - name: Run GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v4
        with:
          targetPath: /tmp/repo
          updateAssemblyInfo: false


      - name: Set up Java 25
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '25'
          cache: maven
          cache-dependency-path: '**/pom.xml'

      - name: Set up Maven 3.9.9
        uses: s4u/setup-maven-action@v1.19.0
        with:
          maven-version: '3.9.9'

      - name: Build with Maven
        run: |
          cd /tmp/repo
          mvn -B clean package -DskipTests -Drevision=${{ steps.gitversion.outputs.fullSemVer }}


      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy build via rsync
        run: |
          VERSION=${{ steps.gitversion.outputs.fullSemVer }}
          BUILD_JAR=$(find /tmp/repo/target -name "*.jar" | head -n 1)
          echo "Deploying version: $VERSION"
          echo "Uploading $BUILD_JAR"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            mkdir -p '${{ secrets.WORK_DIR }}/$VERSION';
            ln -sfn '$VERSION' '${{ secrets.WORK_DIR }}/latest';
          "
          rsync -avz "$BUILD_JAR" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}/$VERSION/


      - name: Restart app on server
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "sudo systemctl restart chatgpt.service"

      - name: Cleanup SSH
        run: rm -rf ~/.ssh
